apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot2-0509
  janus-idp.io/tekton: chatbot2-0509
  backstage.io/kubernetes-id: chatbot2-0509
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chatbot2-0509
resources:
- deployment.yaml
- route.yaml
- service.yaml
