apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: chatbot2-0509
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot2-0509 
  name: chatbot2-0509
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot2-0509 
